### ISSUE TITLE
Does not work with special characters in filename

### ISSUE THREAD

**Issue by mynock** [leonelgalan/cloudfront-signer#12]
The signing signature creation fails when the filename has special characters in it. I'll add an option for this but I don't particularly understand the use cases for why you wouldn't always want to escape the URI before signing.

**Comment by leonelgalan** [comment]
I'm not entirely sure why I wouldn't (I "inherited" the gem), but I will take a look and alias the two methods if at some point I conclude that I should escape the URI every time.

Thanks for your contribution,  I'm a Spanish speaker and this is a welcomed addition.
