### ISSUE TITLE
Warning about Fixnum

### ISSUE THREAD

**Issue by scott-knight** [leonelgalan/cloudfront-signer#14]
I am using Ruby 2.4.1 and Rails 4.2.8. I just upgraded the cloudfront-signer gem to 3.0.1. When running my test suite I am receiving this warning message: 
**gems/cloudfront-signer-3.0.1/lib/cloudfront-signer.rb:247: warning: constant ::Fixnum is deprecated**

**Comment by leonelgalan** [comment]
#15 was merged, thanks for your contribution.
