### ISSUE TITLE
AWS Certificate Manager

### ISSUE THREAD

**Issue by jakeperry** [leonelgalan/cloudfront-signer#16]
Is there anyway to use this with the AWS Certificate Manager to get the certificate?

**Comment by leonelgalan** [comment]
Hi, I haven't used ACM yet. Do you know how the official gem handles it?

**Comment by jakeperry** [comment]
I don't, I was looking into the ACM portion of the gem and could only find a way to pull up the cert but you can't get the Key from the gem or api.

**Comment by leonelgalan** [comment]
Same here, I read that if you import a certificate to ACM, you will use your own key pair. But I guess that defeats the purpose of letting AWS handle everything.

I meant how the official gem handles other products while using ACM, not the ACM part of it per se. For example how do you connect to S3? Maybe wen can see how it allows you to authenticate.

**Comment by leonelgalan** [comment]
Closed for inactivity
